Admin page
466-team1/OptionalKarmotrine pull request #10
Opened 2022-11-22 17:21 UTC by Z1922762

Added views and modifying forms for:

Drink inventory view
Overall order details view
Customer contact details view
Order contents view

Order status modification
Order note modification

Ignore the other changes to other files

2022-11-22 20:45 UTC, Eremeir requested changes
Needs consolidation and CSS revisions before merging back into source branch (session-variable-overhaul)

2022-11-22 20:49 UTC, JamesYahnke approved these changes

2022-11-26 18:19 UTC, 0ttermatic approved these changes

2022-11-26 19:08 UTC, Eremeir approved these changes
Merging back to session-variable-overhaul to take advantage of codebase updates.

2022-11-26 19:08 UTC, merged